# NAME: Steven Chu
# EMAIL: schu92620@gmail.com
# ID: 905094800

default: lab1a.c
	gcc lab1a.c -o lab1a -g -Wall -Wextra

dist: lab1a.c README Makefile
	tar -czvf lab1a-905094800.tar.gz lab1a.c Makefile README

clean:
	rm -f lab1a lab1a-905094800.tar.gz
