#NAME: Steven Chu
#EMAIL: schu92620@gmail.com
#ID: 905094800

default: dist

dist: git.png build_run.png copy.png Makefile my_beaglebone.jpg connected.png README
	tar -czvf lab4a-905094800.tar.gz git.png build_run.png copy.png Makefile my_beaglebone.jpg connected.png README
